CREATE TABLE T_PAIS (ID_PAIS NUMBER PRIMARY KEY,
                NOME_PAIS VARCHAR(30)NOT NULL);
                            
CREATE TABLE T_ESTADO (ID_ESTADO NUMBER PRIMARY KEY,
                NOME_ESTADO VARCHAR(30)NOT NULL,
                ID_PAIS NUMBER);

ALTER TABLE T_ESTADO ADD CONSTRAINT FK_ESATDO FOREIGN KEY
(ID_ESTADO) REFERENCE T_PAIS (ID_PAIS);